name: lobe-chat-database-pgfix
services:
  postgresql:
    image: pgvector/pgvector:pg17
    container_name: lobe-postgres
    ports:
      - '5433:5432'
    volumes:
      - './data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_DB=lobechat'
      - 'POSTGRES_PASSWORD=securepassword123'
      - 'POSTGRES_USER=postgres'
    command: postgres -c 'max_connections=100' -c 'shared_buffers=128MB'
    restart: always
    networks:
      - lobe-network

networks:
  lobe-network:
    driver: bridge
