use_default_settings: false
general:
  debug: false
  instance_name: "LobeChat SearXNG"

server:
  secret_key: "6007ccbb4f8a249a66e968f724b17c567e96d5079dd90a075edc6402fc291bde"
  bind_address: "0.0.0.0:8080"
  base_url: /
  limiter: false
  image_proxy: false
  default_http_headers:
    X-Content-Type-Options: nosniff
    X-XSS-Protection: 1; mode=block
    X-Download-Options: noopen
    X-Robots-Tag: noindex, nofollow
    Referrer-Policy: no-referrer

search:
  safe_search: 0
  autocomplete: "google"
  default_lang: "en"
  formats:
    - html
    - json
    - csv
    - rss

engines:
  - name: google
    engine: google
    shortcut: g
    disabled: false

ui:
  static_use_hash: true
  default_theme: simple
  default_locale: en
  query_in_title: false

doi_resolvers:
  sci-hub.se: https://sci-hub.se/{}
  oadoi.org: https://oadoi.org/{}
  doi.org: https://doi.org/{}

default_doi_resolver: doi.org
